pybuilder/pybuilder

- src/main/python/pybuilder/plugins/python/sphinx_plugin.py
- src/unittest/python/plugins/python/sphinx_plugin_tests.py
This relates to #98 which was a feature request for a Sphinx plugin. It includes changes as per the feedback received on my old dev/sphinxPlugin branch.
The plugin right now is very basic but will hopefully still be useful. I would hope to add some additional functionality in the short term. You'll see here http://sphinx-doc.org/invocation.html for example that sphinx-build offers a myriad of options, some of which there would be a strong case for supporting. Sphinx also has the sphinx-apidoc command which automagically generates rst files for entire projects. Could also be a useful addition and would be used together with the sphinx_generate_documentation task the plugin already exposes.
> Sphinx Plugin

- src/main/python/pybuilder/plugins/python/flake8_plugin.py
- src/main/python/pybuilder/plugins/python/integrationtest_plugin.py
- src/main/python/pybuilder/plugins/python/snakefood_plugin.py
- src/unittest/python/plugins/python/coverage_plugin_tests.py
- src/unittest/python/plugins/python/distutils_plugin_tests.py
- src/unittest/python/plugins/python/flake8_plugin_tests.py
- src/unittest/python/plugins/python/integrationtest_plugin_tests.py
- src/unittest/python/plugins/python/pep8_plugin_tests.py
- src/unittest/python/plugins/python/pyfix_unittest_plugin_tests.py
- src/unittest/python/plugins/python/snakefood_plugin_tests.py
- src/unittest/python/plugins/python/sphinx_plugin_tests.py
- src/unittest/python/plugins/ronn_manpage_plugin_tests.py
adding some new plugin tests to the project
> Plugin coverage

- setup.py
- src/integrationtest/python/should_list_multiple_tasks_for_project_using_core_plugin_tests.py
- src/main/python/pybuilder/plugins/core_plugin.py
- src/main/python/pybuilder/plugins/python/distutils_plugin.py
Adds install task to allow "pyb install"
Adds setup.py to allow pip install git+git://github.com/pybuilder/pybuilder.git@&lt;branch&gt;
Closes pybuilder/pybuilder#154
> Allow installing pybuilder with VCS pip install

- src/main/python/pybuilder/plugins/python/unittest_plugin.py
unittest_runner expects a function that accepts at least one parameter, the first parameter being an output stream
connected to #162, fixes #162
> Improve unit test runner generation #162

- src/integrationtest/python/should_execute_teardown_on_before_failure_tests.py
- src/integrationtest/python/should_execute_teardown_on_task_failure_tests.py
- src/integrationtest/python/should_skip_non_teardown_on_task_failure_tests.py
- src/integrationtest/python/should_suppress_error_during_teardown_tests.py
- src/main/python/pybuilder/core.py
- src/main/python/pybuilder/execution.py
- src/main/python/pybuilder/reactor.py
- src/main/python/pybuilder/utils.py
- src/unittest/python/execution_tests.py
Add unit tests as well
fixes #169, connected to #169
> Add teardown actions and stable action order #169

- setup.py
- src/cmdlinetest/test_help.t
- src/integrationtest/python/should_exclude_optional_task_tests.py
- src/integrationtest/python/should_force_exclude_task_tests.py
- src/integrationtest/python/should_raise_exception_optional_exclude_required_task_tests.py
- src/main/python/pybuilder/cli.py
- src/main/python/pybuilder/core.py
- src/main/python/pybuilder/errors.py
- src/main/python/pybuilder/execution.py
- src/main/python/pybuilder/plugins/core_plugin.py
- src/main/python/pybuilder/reactor.py
- src/unittest/python/execution_tests.py
> Allow to exclude/skip tasks from command-line #171

- .travis.yml
> Kill support for Python 3.2 #177

- src/main/python/pybuilder/plugins/python/unittest_plugin.py
> Final unittest_runner cleanup #173

- build.py
> Release 0.11.0 #161

- build.py
Also update authorship
fixes #180, connected to #180
> Release 0.11.0 claims to support 3.2 #180

- build.py
> Bump version to v0.11.1 #182

- build.py
- src/main/python/pybuilder/excp_util_2.py
- src/main/python/pybuilder/excp_util_3.py
- src/main/python/pybuilder/plugins/core_plugin.py
- src/main/python/pybuilder/plugins/python/distutils_plugin.py
- src/main/python/pybuilder/utils.py
- src/unittest/python/plugins/python/distutils_plugin_tests.py
> Add upload capability to distutils plugin #187

- src/main/python/pybuilder/plugins/python/distutils_plugin.py
- src/unittest/python/plugins/python/distutils_plugin_tests.py
> Broken formatter statement in upload plugin #191

- src/main/python/pybuilder/plugins/python/distutils_plugin.py
> Fix minor logging inconsistency in upload plugin #193

- src/main/python/pybuilder/pluginhelper/external_command.py
- src/main/python/pybuilder/plugins/python/flake8_plugin.py
- src/main/python/pybuilder/plugins/python/python_plugin_helper.py
- src/unittest/python/external_command_tests.py
- src/unittest/python/plugins/python/flake8_plugin_tests.py
- src/unittest/python/plugins/python/python_plugin_helper_tests.py
> Flake8 script file filter properties misbehave #202

- src/main/python/pybuilder/plugins/python/coverage_plugin.py
- src/unittest/python/plugins/python/coverage_plugin_tests.py
> 100% coverage is not 100% #203

- build.py
- src/main/python/pybuilder/plugins/python/coverage_plugin.py
> coverage plugin causes issues during build deleting sys modules #211

- README.md
Still needs to be polished a little but the basics work.
> announce the new (and shiny) pybuilder_aws_lambda_plugin

- src/main/python/pybuilder/plugins/python/python_plugin_helper.py
- src/unittest/python/plugins/python/python_plugin_helper_tests.py
> Flake8 should check for directory existence before including it

- src/integrationtest/python/should_write_setup_file_tests.py
- src/integrationtest/python/should_write_setup_file_with_requirements_tests.py
- src/main/python/pybuilder/core.py
- src/main/python/pybuilder/plugins/python/distutils_plugin.py
- src/unittest/python/plugins/python/distutils_plugin_tests.py
> Allow pre- and post-install setuptools logic

- src/main/python/pybuilder/plugins/python/distutils_plugin.py
- src/unittest/python/plugins/python/distutils_plugin_tests.py
- src/unittest/python/test_utils.py
> Fix incorrect formatter logic, add unit tests

- src/main/python/pybuilder/plugins/python/distutils_plugin.py
> add missing description for upload task

- src/main/python/pybuilder/plugins/python/distutils_plugin.py
- src/unittest/python/plugins/python/distutils_plugin_tests.py
> Specifying upload repository for upload task doesn't work

- .mailmap
For nicer ``git shortlog`` output.
> add initial mailmap file

- build.py
- src/main/python/pybuilder/core.py
> Provide optional "dev" version augmentation

- src/main/python/pybuilder/__init__.py
- src/main/python/pybuilder/cli.py
- src/main/python/pybuilder/core.py
- src/main/python/pybuilder/plugins/python/distutils_plugin.py
- src/main/python/pybuilder/reactor.py
- src/main/python/pybuilder/utils.py
> Upload task needs to be able to handle dev releases

- src/main/python/pybuilder/core.py
- src/main/python/pybuilder/reactor.py
- src/unittest/python/reactor_tests.py
> Allow injecting tasks as dependents

- src/main/python/pybuilder/core.py
- src/main/python/pybuilder/reactor.py
- src/unittest/python/reactor_tests.py
Reverts pybuilder/pybuilder#258
> Revert "Allow injecting tasks as dependents"

- src/cmdlinetest/test_help.t
- src/main/python/pybuilder/cli.py
- src/main/python/pybuilder/reactor.py
> Add "-T" option that shows actual build plan

- src/main/python/pybuilder/plugins/python/unittest_plugin.py
> Error importing unittest: No module named xmlrunner

- build.py
- src/main/python/pybuilder/core.py
- src/main/python/pybuilder/errors.py
- src/main/python/pybuilder/pluginloader.py
- src/main/python/pybuilder/reactor.py
- src/unittest/python/pluginloader_tests.py
- src/unittest/python/reactor_tests.py
> Plugin-specified PyB API version constraints

- setup.py
- src/integrationtest/python/should_raise_exception_optional_exclude_required_task_tests.py
- src/main/python/pybuilder/cli.py
- src/main/python/pybuilder/execution.py
- src/main/python/pybuilder/reactor.py
- src/unittest/python/execution_tests.py
- src/unittest/python/reactor_tests.py
> Optional task exclusion doesn't function correctly

- src/main/python/pybuilder/execution.py
- src/unittest/python/execution_tests.py
> Add ExecutionManager.is_task_in_current_execution_plan

- setup.py
- src/cmdlinetest/test_help.t
- src/main/python/pybuilder/cli.py
- src/main/python/pybuilder/scaffolding.py
> Allow PyB projects to be installed via URL-based install

- src/main/python/pybuilder/core.py
- src/main/python/pybuilder/errors.py
- src/main/python/pybuilder/pluginloader.py
- src/main/python/pybuilder/reactor.py
- src/unittest/python/pluginloader_tests.py
- src/unittest/python/reactor_tests.py
> Add support for installing plugins via VCS

- src/main/python/pybuilder/plugins/python/cram_plugin.py
> Cram should handle test absence gracefully

- .travis.yml
- appveyor.yml
- build.py
- src/main/python/pybuilder/core.py
- src/main/python/pybuilder/pip_utils.py
- src/main/python/pybuilder/pluginloader.py
- src/main/python/pybuilder/plugins/core_plugin.py
- src/main/python/pybuilder/plugins/python/coverage_plugin.py
- src/main/python/pybuilder/plugins/python/cram_plugin.py
- src/main/python/pybuilder/plugins/python/flake8_plugin.py
- src/main/python/pybuilder/plugins/python/frosted_plugin.py
- src/main/python/pybuilder/plugins/python/install_dependencies_plugin.py
- src/main/python/pybuilder/plugins/python/pep8_plugin.py
- src/main/python/pybuilder/plugins/python/pychecker_plugin.py
- src/main/python/pybuilder/plugins/python/pyfix_unittest_plugin.py
- src/main/python/pybuilder/plugins/python/pylint_plugin.py
- src/main/python/pybuilder/plugins/python/pymetrics_plugin.py
- src/main/python/pybuilder/plugins/python/pytddmon_plugin.py
- src/main/python/pybuilder/plugins/python/snakefood_plugin.py
- src/main/python/pybuilder/plugins/python/sphinx_plugin.py
- src/main/python/pybuilder/plugins/python/stdeb_plugin.py
- src/main/python/pybuilder/plugins/python/unittest_plugin.py
- src/unittest/python/pip_utils_tests.py
- src/unittest/python/plugins/python/flake8_plugin_tests.py
- src/unittest/python/plugins/python/pep8_plugin_tests.py
- src/unittest/python/plugins/python/pyfix_unittest_plugin_tests.py
- src/unittest/python/plugins/python/snakefood_plugin_tests.py
Also: Env is not inherited properly by integrationtest plugin for PyB
fixes #272, connected to #272
fixes #284, connected to #284
> PyB plugins use wrong external tool dependencies

- appveyor.yml
Tests in Py33+. More work required for Py26+.
> test on multiple pythons on Windows OS

- src/main/python/pybuilder/utils.py
- src/unittest/python/utils_tests.py
> Execute_command should handle None-output better

- src/main/python/pybuilder/plugins/python/cram_plugin.py
- src/unittest/python/plugins/python/cram_plugin_tests.py
fixes #291, connected to #291, connected to #281
> Issue #281 does not disable cram tests properly

- src/main/python/pybuilder/pip_utils.py
- src/main/python/pybuilder/plugins/core_plugin.py
- src/unittest/python/pip_utils_tests.py
fixes #293, connected to #293, connected to #272
> Harden and optimize use of `search_packages_info` in #272

- src/main/python/pybuilder/pip_utils.py
fixes #295, connected to #295, connected to #272, connected to #293
> Need to reinitialize PIP workset in pip_utils

- src/main/python/pybuilder/plugins/python/install_dependencies_plugin.py
- src/unittest/python/plugins/python/install_dependencies_plugin_tests.py
fixes #299, connected to #299, connected to #297
> install_dependencies_plugin should use environment

- src/main/python/pybuilder/plugins/python/coverage_plugin.py
- src/unittest/python/plugins/python/coverage_plugin_tests.py
> PyB coverage plugin should exclude namespaces

- src/main/python/pybuilder/pip_utils.py
Fixes #303
Connected to #303 and #297
> add pip executable suffix on windows

- setup.py
- src/main/python/pybuilder/scaffolding.py
Also updates PyB setup.py
fixes #306, connected to #306
> Generated setup.py needs to handle pip on Windows

- src/main/python/pybuilder/plugins/python/pylint_plugin.py
- src/unittest/python/plugins/python/pylint_plugin_tests.py
> honor pylint options #314

- build.py
- src/main/python/pybuilder/core.py
Attempted to fix a couple of issues that at least allow the testing to progress when run on Windows.
> Windows fixes to allow testing to progress

- src/main/python/pybuilder/utils.py
> Fixing segmentation fault under Cygwin - fix #321

- src/main/python/pybuilder/plugins/python/distutils_plugin.py
- src/unittest/python/plugins/python/distutils_plugin_tests.py
> Add ability to customize packaging options ad nauseam

- src/main/python/pybuilder/utils.py
> Fixing segmentation fault under Msys2

- src/main/python/pybuilder/plugins/python/distutils_plugin.py
- src/unittest/python/plugins/python/distutils_plugin_tests.py
> PyB distutils plugin upload signing

- src/main/python/pybuilder/scaffolding.py
I'd like to be informed when the setup.py is created.
> print a message when creating setup.py

- .travis.yml
- README.md
- build.py
WIP - do not merge (PR to trigger travis)
> try out 3.5 compatibility

- src/main/python/pybuilder/pluginloader.py
- src/main/python/pybuilder/reactor.py
- src/unittest/python/pluginloader_tests.py
> Unable to specify version for custom plugin

- src/main/python/pybuilder/reactor.py
- src/unittest/python/reactor_tests.py
> @dependents ignores customized task name

- src/main/python/pybuilder/plugins/core_plugin.py
- src/main/python/pybuilder/plugins/python/install_dependencies_plugin.py
- src/main/python/pybuilder/plugins/python/sphinx_plugin.py
- src/main/python/pybuilder/plugins/python/stdeb_plugin.py
- src/main/python/pybuilder/utils.py
> Fix path separators and protect log file names on Windows

- build.py
- src/main/python/pybuilder/pip_common.py
- src/main/python/pybuilder/pip_utils.py
- src/main/python/pybuilder/plugins/python/install_dependencies_plugin.py
- src/unittest/python/pip_utils_tests.py
- src/unittest/python/pluginloader_tests.py
- src/unittest/python/plugins/python/install_dependencies_plugin_tests.py
- src/unittest/python/test_utils.py
> Recursive dependency upgrades should be subject to global version constraints

- build.py
- src/integrationtest/python/should_write_namespace_packages_tests.py
- src/integrationtest/python/should_write_setup_file_with_requirements_tests.py
- src/main/python/pybuilder/core.py
- src/main/python/pybuilder/plugins/python/distutils_plugin.py
- src/main/python/pybuilder/reactor.py
- src/unittest/python/plugins/python/distutils_plugin_tests.py
> python.distutils plugin doesn't support `namespace_packages`

- src/main/python/pybuilder/plugins/python/distutils_plugin.py
> Pathing issues on pypi upload on Windows

- src/main/python/pybuilder/core.py
- src/main/python/pybuilder/utils.py
> Harden expand_path for Windows and safe_log_file_name

- src/cmdlinetest/test_help.t
- src/main/python/pybuilder/cli.py
- src/main/python/pybuilder/terminal.py
- src/unittest/python/cli_tests.py
> Color escape sequence not properly terminated

- src/main/python/pybuilder/plugins/python/sphinx_plugin.py
- src/unittest/python/plugins/python/sphinx_plugin_tests.py
> Wrong logging level for sphinx_generate_documentation

- src/main/python/pybuilder/plugins/python/sphinx_plugin.py
- src/unittest/python/plugins/python/sphinx_plugin_tests.py
> Fix paths in the Sphinx PyB quickstart and runtime configuration

- src/main/python/pybuilder/core.py
- src/unittest/python/plugins/python/install_dependencies_plugin_tests.py
> Wrong dependency version error formatting

- .travis.yml
- build.py
- src/main/python/pybuilder/plugins/python/distutils_plugin.py
> Generate package summary and description based on a README.md

- src/cmdlinetest/test_help.t
- src/main/python/pybuilder/cli.py
- src/main/python/pybuilder/reactor.py
- src/unittest/python/reactor_tests.py
> Allow to append build targets to default from command line

- src/main/python/pybuilder/pip_common.py
- src/main/python/pybuilder/pip_utils.py
- src/main/python/pybuilder/plugins/python/install_dependencies_plugin.py
- src/unittest/python/pip_utils_tests.py
- src/unittest/python/pluginloader_tests.py
- src/unittest/python/plugins/python/install_dependencies_plugin_tests.py
> Uptake new PIP upgrade features

- build.py
project name has to be exactly the same as repository folder name
> project name fix

- src/integrationtest/python/should_build_pyfix_project_tests.py
- src/integrationtest/python/should_build_simple_python_project_tests.py
- src/integrationtest/python/should_exclude_optional_task_tests.py
- src/integrationtest/python/should_filter_resources_tests.py
- src/integrationtest/python/should_invoke_initializer_when_environments_match_tests.py
- src/integrationtest/python/should_list_multiple_tasks_for_project_using_core_plugin_tests.py
- src/integrationtest/python/should_list_multiple_tasks_for_simple_project_tests.py
- src/integrationtest/python/should_list_single_task_for_simple_project_tests.py
- src/integrationtest/python/should_not_invoke_initializer_when_environment_do_not_match_tests.py
- src/integrationtest/python/should_raise_exception_when_no_default_goal_is_given_tests.py
- src/integrationtest/python/should_raise_exception_when_project_is_not_valid_tests.py
- src/integrationtest/python/should_set_pyfix_glob_from_suffix_tests.py
- src/integrationtest/python/should_skip_non_teardown_on_task_failure_tests.py
- src/integrationtest/python/should_skip_undefined_keys_when_filtering_tests.py
- src/integrationtest/python/should_suppress_error_during_teardown_tests.py
- src/integrationtest/python/should_write_manifest_file_tests.py
- src/integrationtest/python/should_write_setup_file_tests.py
- src/integrationtest/python/should_write_setup_file_with_requirements_tests.py
- src/main/python/pybuilder/plugins/python/flake8_plugin.py
- src/unittest/python/plugins/python/flake8_plugin_tests.py
> Flake8 3.2.0 broke the build

- src/integrationtest/python/should_write_namespace_packages_tests.py
- src/integrationtest/python/should_write_setup_file_tests.py
- src/integrationtest/python/should_write_setup_file_with_requirements_tests.py
- src/main/python/pybuilder/plugins/python/distutils_plugin.py
- src/unittest/python/plugins/python/distutils_plugin_tests.py
> python.distutils plugin: setup.py keywords

- src/main/python/pybuilder/plugins/python/distutils_plugin.py
- src/unittest/python/plugins/python/distutils_plugin_tests.py
Register command was added before upload
Issue: https://github.com/pybuilder/pybuilder/issues/430
> distutils: register command was added before upload

- README.md
> Fix PyPI documentation

- src/main/python/pybuilder/plugins/python/coverage_plugin.py
> Coverage plugin fails when fails to load covered module

- build.py
> Copy resource doesn't include the LICENSE file in the distro

- .travis.yml
- build.py
> Add Python 3.6 support

- build.py
- src/integrationtest/python/should_write_namespace_packages_tests.py
- src/integrationtest/python/should_write_setup_file_tests.py
- src/integrationtest/python/should_write_setup_file_with_requirements_tests.py
- src/main/python/pybuilder/core.py
- src/main/python/pybuilder/plugins/python/distutils_plugin.py
- src/main/python/pybuilder/reactor.py
- src/unittest/python/plugins/python/distutils_plugin_tests.py
> Allow specifying python version constraint

- build.py
> PyBuilder needs to depend on modern setuptools

- src/integrationtest/python/should_write_namespace_packages_tests.py
- src/integrationtest/python/should_write_setup_file_tests.py
- src/integrationtest/python/should_write_setup_file_with_requirements_tests.py
- src/main/python/pybuilder/core.py
- src/main/python/pybuilder/plugins/python/distutils_plugin.py
- src/main/python/pybuilder/reactor.py
- src/unittest/python/plugins/python/distutils_plugin_tests.py
> Allow obsoleting packages with "obsoletes"

- build.py
> Update setuptools to ~=34.0

- build.py
> Move setuptools to 35.x

- src/main/python/pybuilder/execution.py
- src/main/python/pybuilder/utils.py
- src/unittest/python/utils_tests.py
This will make master go green again.
> remove all bare exceptions to make new flake8 happy

- src/main/python/pybuilder/plugins/python/coverage_plugin.py
> Restrict to all versions less than 4.4.2 temporarily

- src/main/python/pybuilder/plugins/python/coverage_plugin.py
> Coverage 4.4.2 and fails without __main__ in modules

- build.py
- src/main/python/pybuilder/plugins/python/coverage_plugin.py
> Fix for #523 for 0.11 branch

- .travis.yml
- travis_build.sh
> Add native Travis deployment

- .travis.yml
> Try updating Travis TWINE credentials

- .travis.yml
> Underscore in username

- src/main/python/pybuilder/vcs.py
This implements access to `git describe` with some useful options. Usually, it looks for available git tags (tag objects), but there are some fall-backs that are activated to make it more robust.
* `--allways`: Show uniquely abbreviated commit object as fallback.
* `--tags`: Instead of using only the annotated tags, use any tag found in refs/tags namespace. This option enables matching a lightweight (non-annotated) tag.
* `--dirty`:            Describe the working tree. It means describe HEAD and appends `--dirty` if the working tree is dirty.
So, for example, while developing this feature, I get the following: `v0.11.10-30-g8bec37a30b-dirty`.
This means: when descending the git DAG the first that was found was `v0.11.10`, this commit is `30` commits ahead of that tag, `g` means this is …
> implement PyBuilder access to git describe

- build.py
- src/main/python/pybuilder/plugins/python/coverage_plugin.py
- src/main/python/pybuilder/plugins/python/distutils_plugin.py
- src/main/python/pybuilder/plugins/python/flake8_plugin.py
- src/main/python/pybuilder/plugins/python/sphinx_plugin.py
- src/unittest/python/plugins/python/flake8_plugin_tests.py
Setuptools ~=38.5
Twine ~= 1.10
Flake ~= 3.5
Coverage ~= 4.5
> Bump dependencies

- src/integrationtest/python/should_raise_exception_when_detect_task_cycle_tests.py
- src/main/python/pybuilder/cli.py
- src/main/python/pybuilder/errors.py
- src/main/python/pybuilder/execution.py
- src/main/python/pybuilder/graph_utils.py
- src/main/python/pybuilder/plugins/python/distutils_plugin.py
- src/unittest/python/graph_utils_tests.py
> Fix silent failure in loop-detection dependency

- build.py
- src/integrationtest/python/should_raise_exception_when_detect_task_cycle_tests.py
- src/main/python/pybuilder/cli.py
- src/main/python/pybuilder/errors.py
- src/main/python/pybuilder/execution.py
- src/main/python/pybuilder/graph_utils.py
- src/main/python/pybuilder/plugins/core_plugin.py
- src/main/python/pybuilder/plugins/python/distutils_plugin.py
- src/main/python/pybuilder/plugins/python/sphinx_plugin.py
- src/main/python/pybuilder/utils.py
- src/unittest/python/graph_utils_tests.py
>  Fix silent failure in loop-detection dependency

- appveyor.yml
- build.py
> Workaround PIP 10

- build.py
- src/main/python/pybuilder/pip_common.py
Add version-matching hack.
fixes #586
> Do make PyB 0.11 work with PIP 10.

- setup.py
- src/main/python/pybuilder/scaffolding.py
> Make sure to handle result code 127 in detecting that PyB isn't present

- build.py
- src/main/python/pybuilder/plugins/python/distutils_plugin.py
> Fix Twine and wheel dependencies

- README.md
> Fix links in README to point to the new domain

- .travis.yml
- src/integrationtest/python/base_itest_support.py
- src/integrationtest/python/itest_support.py
- src/integrationtest/python/should_build_project_with_script_named_like_library_tests.py
- src/integrationtest/python/should_build_simple_python_project_tests.py
- src/integrationtest/python/should_exclude_optional_task_tests.py
- src/integrationtest/python/should_execute_teardown_on_before_failure_tests.py
- src/integrationtest/python/should_execute_teardown_on_task_failure_tests.py
- src/integrationtest/python/should_filter_resources_tests.py
- src/integrationtest/python/should_force_exclude_task_tests.py
- src/integrationtest/python/should_gracefully_fail_when_no_remote_plugin_tests.py
- src/integrationtest/python/should_ignore_hidden_files_in_scripts_tests.py
- src/integrationtest/python/should_invoke_initializer_when_environments_match_tests.py
- src/integrationtest/python/should_list_multiple_tasks_for_project_using_core_plugin_tests.py
- src/integrationtest/python/should_list_multiple_tasks_for_simple_project_tests.py
- src/integrationtest/python/should_list_single_task_for_simple_project_tests.py
- src/integrationtest/python/should_not_invoke_initializer_when_environment_do_not_match_tests.py
- src/integrationtest/python/should_raise_exception_optional_exclude_required_task_tests.py
- src/integrationtest/python/should_raise_exception_when_detect_task_cycle_tests.py
- src/integrationtest/python/should_raise_exception_when_no_default_goal_is_given_tests.py
- src/integrationtest/python/should_skip_non_teardown_on_task_failure_tests.py
- src/integrationtest/python/should_skip_undefined_keys_when_filtering_tests.py
- src/integrationtest/python/should_support_annotated_tasks_and_actions_tests.py
- src/integrationtest/python/should_suppress_error_during_teardown_tests.py
- src/integrationtest/python/should_write_manifest_file_tests.py
- src/integrationtest/python/should_write_namespace_packages_tests.py
- src/integrationtest/python/should_write_setup_file_tests.py
- src/integrationtest/python/should_write_setup_file_with_requirements_tests.py
- src/integrationtest/python/smoke_clean_tests.py
- src/integrationtest/python/smoke_itest_support.py
Add smoke tests for non-synthetic testing of the build script
Add supporting infrastructure for the tests
> Bump test version of Python to 3.8.2

- build.py
- src/integrationtest/python/smoke_install_dependencies_tests.py
- src/main/python/pybuilder/plugins/python/install_dependencies_plugin.py
> Fix install dependencies not having a prepare and not creating target directories

- src/main/python/pybuilder/_vendor/colorama/__init__.py
- src/main/python/pybuilder/_vendor/colorama/ansi.py
- src/main/python/pybuilder/_vendor/colorama/ansitowin32.py
- src/main/python/pybuilder/_vendor/colorama/initialise.py
- src/main/python/pybuilder/_vendor/colorama/win32.py
- src/main/python/pybuilder/_vendor/colorama/winterm.py
- src/main/python/pybuilder/_vendor/virtualenv.py
- src/main/python/pybuilder/cli.py
- src/main/utils/vendorize.toml
Update VirtualEnv
Add Colorama on Windows when stdout is a TTY
fixes #660
> Vendorize Colorama

- src/main/python/pybuilder/cli.py
- src/unittest/python/cli_tests.py
> Imrove error message reporting on failure

- src/integrationtest/python/should_not_load_remote_classes_in_unittest_on_error_tests.py
- src/integrationtest/python/should_not_load_remote_classes_in_unittest_tests.py
- src/main/python/pybuilder/plugins/python/remote_tools/__init__.py
- src/main/python/pybuilder/plugins/python/remote_tools/unittest_tool.py
- src/main/python/pybuilder/plugins/python/unittest_plugin.py
- src/main/python/pybuilder/remote/__init__.py
- src/main/python/pybuilder/scaffolding.py
- src/unittest/python/plugins/python/unittest_plugin_tests.py
> Unittests need to run in the 'build' environment.

- README.md
- build.py
- src/integrationtest/python/smoke_sphinx_pyb_quickstart_tests.py
- src/integrationtest/python/smoke_sphinx_pyb_quickstart_with_api_doc_tests.py
- src/integrationtest/python/smoke_sphinx_quickstart_tests.py
- src/main/python/pybuilder/plugins/python/sphinx_plugin.py
- src/main/python/pybuilder/python_env.py
- src/main/python/pybuilder/python_utils.py
- src/unittest/python/plugins/python/sphinx_plugin_tests.py
- travis/travis_shim.py
Update README with logos
Bump version
fixes #691
> Fix Sphinx invocation using obsolete non-existent modules.

- build.py
- src/main/python/pybuilder/cli.py
- src/unittest/python/cli_tests.py
> CLI -P containing equals sign fails to parse properly

- .travis.yml
- src/main/python/pybuilder/utils.py
> Bump Python test versions 2020-06-09

- src/main/python/pybuilder/plugins/python/coverage_plugin.py
- src/main/python/pybuilder/plugins/python/coveralls_plugin.py
- src/main/python/pybuilder/plugins/python/unittest_plugin.py
- src/main/python/pybuilder/remote/__init__.py
- src/unittest/python/plugins/python/unittest_plugin_tests.py
Upgrade Coverage, Unittest XML, Coveralls
fixes #735
> Fix remote getting too excited and classifying classes as callable methods

- .travis.yml
- src/main/python/pybuilder/extern/__init__.py
- src/main/python/pybuilder/plugins/python/integrationtest_plugin.py
- src/main/python/pybuilder/plugins/python/pdoc_plugin.py
- src/unittest/python/plugins/python/pdoc_plugin_tests.py
- travis/travis_install.sh
> PDoc to PDoc3 migration for Pythons > 2.x

- src/main/python/pybuilder/plugins/python/distutils_plugin.py
- travis/travis_install.cmd
> Fixes "artifcats" typo

- .github/workflows/pybuilder.yml
- gha_build.py
- src/main/python/pybuilder/python_env.py
Split stable and experimental jobs
Disable experimental jobs for PRs
Add Homebrew to MacOS
> Rework GHA workflow

- src/integrationtest/python/base_itest_support.py
Add uuid4 with dashes removed to the suffix
fixes #788
> In integration test suite ensure there are no trailing underscores

- src/integrationtest/python/issue_768_module_tests.py
- src/integrationtest/python/issue_768_package_tests.py
- src/integrationtest/python/should_copy_symlinked_directories_tests.py
- src/main/python/pybuilder/plugins/python/core_plugin.py
- src/unittest/python/plugins/python/core_plugin_tests.py
Modules are all modules that are not in packages, recursively
Packages are all packages that contain __init__.py
Process symlinks
Add integration tests
fixes #768
> Rework list_modules, list_packages and list_scripts

- build.py
> All vendored artifacts need to be included in the final package

- src/main/python/pybuilder/plugins/python/core_plugin.py
> Do not register an unpopulated VEnv

- .github/workflows/pybuilder.yml
- build.py
> Update deploy token

- .github/workflows/pybuilder.yml
- README.md
PyPy 3.7 moved from experimental
> Python 3.10

- .github/action.yml
- .github/workflows/pybuilder.yml
- src/main/python/pybuilder/python_env.py
Add PyPy 3.8
Fix site-packages in PyPy
> GHA now allows conditional actions, Add PyPy 3.8

- src/integrationtest/python/smoke_clean_tests.py
- src/main/python/pybuilder/plugins/python/coverage_plugin.py
- src/main/python/pybuilder/plugins/python/coveralls_plugin.py
Upgrade coveralls to ~=3.0 for compatibility
Workaround for coveralls issue
fixes #826
> Upgrade coverage to ~=6.0

- .github/workflows/pybuilder.yml
- src/integrationtest/python/should_write_namespace_packages_tests.py
- src/integrationtest/python/should_write_setup_file_tests.py
- src/integrationtest/python/should_write_setup_file_with_requirements_tests.py
- src/main/python/pybuilder/plugins/python/distutils_plugin.py
- src/main/python/pybuilder/plugins/python/vendorize_plugin.py
long_description must be specified since setuptools 62.2+
either set it to summary or to project name
fixes #852
> Make sure that project.description is always set

- src/integrationtest/python/issue_868_tests.py
- src/main/python/pybuilder/terminal.py
> Make sure to auto-close the file

- .github/workflows/pybuilder.yml
- src/main/python/pybuilder/python_env.py
> Managed venvs will now distinguish between debug and release versions of Python

- .github/workflows/pybuilder.yml
- build.py
- src/main/python/pybuilder/core.py
- src/main/python/pybuilder/pip_utils.py
- src/unittest/python/pip_utils_tests.py
Constraints are generated without extras
fixes #912
> Take extras into consideration for Dependency
