pybuilder/pybuilder

src/main/python/pybuilder/vcs.py
src/unittest/python/vcs_tests.py

The --count option was not supported, counting internally now.
I also added error output in case git or subversion did not work as expected.

Fix autoversioning for older git version like found on RHEL6

---

src/main/python/pybuilder/plugins/python/integrationtest_plugin.py

Getting integration test output is sometimes useful even when they don't fail. Without this feature, you have to intentionally break the integration test to see the output.

Add option for always printing integration test output

---

src/main/python/pybuilder/plugins/python/pycharm_plugin.py
src/unittest/python/plugins/python/pycharm_plugin_tests.py

Generate entries for unit and integration test directories (if respective plugins are activated) and mark them as test sources

Pycharm test dirs

---

src/main/python/pybuilder/plugins/python/unittest_plugin.py
src/unittest/python/plugins/python/unittest_plugin_tests.py

Monkeypatch unittest runner classes instead of hardcoding internal Runner and Result
Allow to specify custom TextTestRunner-based class as a runner
Allow to specify a custom Result factory runner method
Add unit test coverage
"unittest_runner" property can be set to:
* class
* class name
* tuple of class/class-name and
* name of the runner result-generating factory method
* unbound method object with desired name
* function with desired name
Runner class defaults to unittest.TextTestRunner
Result object factory method name defaults to "_makeResult"
Example:
```python
project.set_property("unittest_runner", (lambda: xmlrunner.XMLTestRunner(project.get_property("dir_target")), xmlrunner.XMLTestRunner._make_result))
```

Allow to specify a custom unittest runner

---

src/main/python/pybuilder/execution.py
src/main/python/pybuilder/plugins/python/coverage_plugin.py
src/main/python/pybuilder/plugins/python/unittest_plugin.py
src/main/python/pybuilder/reactor.py
src/unittest/python/execution_tests.py
src/unittest/python/plugins/python/unittest_plugin_tests.py

Fix coverage not failing when forked
Make unittest and coverage library functions

Issues #146, #147, #149 and #150

---

build.py
src/main/python/pybuilder/__init__.py
src/main/python/pybuilder/errors.py
src/main/python/pybuilder/excp_util_2.py
src/main/python/pybuilder/excp_util_3.py
src/main/python/pybuilder/plugins/python/coverage_plugin.py
src/main/python/pybuilder/plugins/python/unittest_plugin.py
src/main/python/pybuilder/utils.py
src/unittest/python/utils_tests.py

Forking option in coverage and unittest is now deprecated (removed in unittest since never made public)
Coverage will always fork
Unittest will always fork unless is already forked in coverage
utils.fork_process is now used in both to capture exit code, returned value and possible exception (with traceback) from a forked process
Module reloading is removed since it doesn't ever work when modules keep state and rely on intermodule dependencies
This should be a problem since coverage and unittests run in different forks and will reinitialize the modules anyway
Closes pybuilder/pybuilder#150, closes pybuilder/pybuilder#151

Fixes issues #150, #151, #156 and #160

---

src/main/python/pybuilder/plugins/python/stdeb_plugin.py
src/unittest/python/plugins/python/stdeb_plugin_tests.py

Hi,
i’ve wrote a new pybuilder plugin, with this plugin it's now possible to build debian packages of you pybuilder based project.
the stdeb plugin (```use_plugin("python.stdeb”)```) provides a new task called ```make_deb``` and some new properties:
```deb_package_maintainer```, ```path_final_build```, ```path_to_source_tarball```
you can overwrite the default values in your build.py 
To use the plugin you need an debian based operating system (tested on debian 8 and ubuntu 15.04) with the following packages installed:
- dpkg-dev
- python-setuptools, python-all, debhelper
We can’t resolv this requirements with pybuilder tools, because we can’t check for installed os packages. i've used ```assert_can_execute```to check for the most but not every packages provides executables
If you like to …

New plugin stdeb

---

src/main/python/pybuilder/plugins/python/coverage_plugin.py
src/main/python/pybuilder/plugins/python/unittest_plugin.py
src/main/python/pybuilder/utils.py
src/unittest/python/utils_tests.py

As per #184, forking support is so bad (the runtime needs to pickle
**everything**) that it's preferable to trade off some reliability
(this might falsify coverage statistics) so that windows users can
still build projects. On linux/OSX nothing changed, and coverage should
still be as accurate as possible.

Don't fork on windows

---

src/main/python/pybuilder/core.py
src/unittest/python/core_tests.py

We encountred a problem when using the task decorator in the form:
```
@task(description='spam')
def ham():
pass
```
In this case, the name of the task is ommitted and pybuilder cannot cope with
such a task.
The error message in such a case is:
```
PyBuilder version 0.11.2
Build started at 2015-11-04 14:58:23
------------------------------------------------------------
------------------------------------------------------------
BUILD FAILED - expected string or buffer
------------------------------------------------------------
Build finished at 2015-11-04 14:58:23
Build took 0 seconds (104 ms)
```
Please have a look at the solution and perhaps suggest an alterntive. (Yes, I
agree the code is a mindf**k right now) Albeight the tests are actually fairly
readable.

extend and test the task decorator

---

src/integrationtest/python/should_list_multiple_tasks_for_project_using_core_plugin_tests.py
src/main/python/pybuilder/core.py
src/main/python/pybuilder/plugins/core_plugin.py
src/unittest/python/core_tests.py

Depends on fix_task_decorator at #235

Print paths as suggested in #208

---

appveyor.yml

I got pybuilder to run on Appveyor CI for Windows with a basic appveyor.yml.
Currently it only tests against Python 35 and I think there are still some glitches with installing all deps, but maybe you are interested. Someone has to add the Appveyor integration here.

add appveyor config

---

README.md

We renamed the plugin today, the older 'version' has been deprecated.

rename aws plugin

---

src/cmdlinetest/test_help.t
src/main/python/pybuilder/cli.py
src/main/python/pybuilder/execution.py
src/main/python/pybuilder/reactor.py

Using `-o/--exclude-all-optional` should exclude all optional tasks

---

src/main/python/pybuilder/cli.py

Pybuilder does not parse/run tasks when run in Thoughtworks Go

---

src/integrationtest/python/should_support_annotated_tasks_and_actions_tests.py
src/main/python/pybuilder/execution.py

Must use getfullargspec() on Py3.5 with annotations

---

src/main/python/pybuilder/pip_utils.py
src/unittest/python/pip_utils_tests.py

out-of-process PIP install should inherit PyB environment
fixes #297, connected to #297

install dependencies behind proxy

---

src/main/python/pybuilder/plugins/python/distutils_plugin.py
src/unittest/python/plugins/python/distutils_plugin_tests.py

Allow dynamic discovery entry_points configuration

---

src/main/python/pybuilder/pip_utils.py
src/main/python/pybuilder/plugins/python/install_dependencies_plugin.py
src/main/python/pybuilder/scaffolding.py
src/unittest/python/pluginloader_tests.py
src/unittest/python/plugins/python/distutils_plugin_tests.py
src/unittest/python/plugins/python/install_dependencies_plugin_tests.py

`PIP_EXECUTABLE` is no more, replaced with `sys.executable, '-m', 'pip'`
Unit tests updated
Setup.py scaffolding updated
fixes #310, connected to #310

Task install_dependencies doesn't work in version 0.11.3

---

src/main/python/pybuilder/pluginloader.py
src/main/python/pybuilder/plugins/core_plugin.py
src/main/python/pybuilder/plugins/python/distutils_plugin.py
src/unittest/python/pluginloader_tests.py
src/unittest/python/plugins/python/distutils_plugin_tests.py

install_dependencies_(extra_)index_url should affect all PIP operations

---

src/main/python/pybuilder/plugins/python/cram_plugin.py
src/unittest/python/plugins/python/cram_plugin_tests.py

This modification instructs `cram` to use the 'outside' environment variables, without which commands with UTF-8 encoded characters get encoded with their surrogate-escape counterparts, resulting in automated tests failing.
For details, see https://github.com/brodie/cram/issues/7.
Until this pull request is not merged, `afp-cli` won't build.

Update cram plugin to use the 'outside' environment

---

src/main/python/pybuilder/plugins/python/cram_plugin.py
src/unittest/python/plugins/python/cram_plugin_tests.py

- with the option `cram_run_test_from_target` to True (default is False)
cram tests will be executed using the built artifact to be found in
the target directory
- this way, filtered scripts
(http://pybuilder.github.io/documentation/plugins.html#Filteringfiles)
which contain needed information for the tests, can be used.

Adding the flag for cram to run tests from the target directory

---

src/main/python/pybuilder/plugins/python/unittest_plugin.py

Version 2.0 of unittest-xml-reporting has [dropped support for Python 2.6](https://github.com/xmlrunner/unittest-xml-reporting/commit/531895eaccf54aeff7d31b5560a90fc1da720eeb). To work around that, pybuilder's unittest plugin should use an older version when Python2.6 is used.

Work around unittest-xml-reporting 2.0 dropping Python 2.6 support

---

src/main/python/pybuilder/scaffolding.py

The setup.py generated is buggy, apparently:
https://github.com/ImmobilienScout24/afp-cli/pull/57

FileNotFoundError doesn't exist (in python?)

---

src/main/python/pybuilder/pip_utils.py
src/main/python/pybuilder/pluginloader.py
src/main/python/pybuilder/plugins/python/install_dependencies_plugin.py
src/unittest/python/pip_utils_tests.py
src/unittest/python/pluginloader_tests.py
src/unittest/python/plugins/python/install_dependencies_plugin_tests.py

This also changes the following behaviors:
* extra-index-url is now supported without specifying index-url
* trusted-host and extra-index-url can specify both a single value and a collection as pip allows that
trusted-host added for both dependency and plugin installs
fixes #341, connected to #341

Support for pip --trusted-host argument enhancement

---

src/main/python/pybuilder/plugins/python/sphinx_plugin.py
src/unittest/python/plugins/python/sphinx_plugin_tests.py

Sphinx indicates failure with -v but not without it

---

src/main/python/pybuilder/execution.py
src/main/python/pybuilder/reactor.py
src/unittest/python/execution_tests.py
src/unittest/python/reactor_tests.py

@dependents does not inject dependencies from plugin if task is already defined earlier

---

src/main/python/pybuilder/plugins/python/distutils_plugin.py
src/unittest/python/plugins/python/distutils_plugin_tests.py

Entry-points should handle a single entry correctly

---

src/main/python/pybuilder/vcs.py

Anyone interested in this? I'd write some unit tests if people would want to use this.

implement get_git_hash

---

src/main/python/pybuilder/scaffolding.py

This fixes a bug in corner case in the `setup.py` shim/scaffolding generated by
PyBuilder. When using `install_file` and friends and installing the project via
git+ssh protocol the scaffolding `setup.py` crashes during cleanup, because
certain directories are non-empty.
In order to further demonstrate the issue, I have created a PyBuilder project
at:
https://github.com/esc/pybuilder-bug-expose
If you now try to install this project, you get:
```
% pip install "git+ssh://git@github.com/esc/pybuilder-bug-expose.git#egg=bug"
Collecting bug from git+ssh://git@github.com/esc/pybuilder-bug-expose.git#egg=bug
Cloning ssh://git@github.com/esc/pybuilder-bug-expose.git to /tmp/pip-build-BE_AGP/bug
Complete output from command python setup.py egg_info:
pyb 0.11.8
PyBuilder version 0.11.8
Build …
```

use shutil.rmtree instead of os.removedirs

---

src/main/python/pybuilder/core.py

extracted explicit root_path in order to fill manifest and setup.py only with relative paths according to package structure

include_directory fix for manifest and setup.py

---

src/main/python/pybuilder/vcs.py

I think this is my current best take on CLD version numbers. Using the commit-count enables moving forward all the time and using the travis build-count means we get repeatable builds that can always upload a build-artifact. Since I am using this idiom in all of our projects right now, I am proposing that we include this in PyBuilder.

adding count_travis

---

src/main/python/pybuilder/plugins/python/coverage_plugin.py
src/unittest/python/plugins/python/coverage_plugin_tests.py

Coverage for missing modules should cause a failure

---

src/main/python/pybuilder/coverage_utils.py
src/main/python/pybuilder/plugins/python/coverage_plugin.py

Coverage should be setup to cover multiprocessing and forks

---

src/main/python/pybuilder/plugins/python/sphinx_plugin.py
src/unittest/python/plugins/python/sphinx_plugin_tests.py

Sphinx configuration should share PyB at runtime #398

---

src/main/python/pybuilder/plugins/python/distutils_plugin.py

Pypandoc updated to ~=1.3.0
fixes #428

PyBuilder's setup.py broken when pandoc>=1.18 is installed with pypandoc~=1.2.0

---

src/cmdlinetest/test_help.t
src/main/python/pybuilder/cli.py
src/main/python/pybuilder/reactor.py
src/unittest/python/reactor_tests.py

Allow modifying default targets similar to manner of adding them in #412

---

src/unittest/python/vcs_tests.py

Just getting the hang of doing development on this tree.  Thought I'd pick a file and finish its test coverage.

Increasing test coverage on vcs_tests.py

---

src/main/python/pybuilder/plugins/python/flake8_plugin.py
src/unittest/python/plugins/python/flake8_plugin_tests.py

Property by default is disabled, so if the user does not define it on build.py it will not affect the code.
But if the user adds a value it will set the code complexity parameter to check over the code

Exposing Flake8 Code Complexity Property

---

src/main/python/pybuilder/plugins/python/distutils_plugin.py

fixes: https://github.com/pybuilder/pybuilder/issues/487
using / as path separator in setup.py which is according to doc: http://setuptools.readthedocs.io/en/latest/setuptools.html (look for 'you must use a forward slash')

[487] using / as path separator in setup.py

---

.mailmap
src/integrationtest/python/integrationtest_support.py
src/main/python/pybuilder/plugins/python/distutils_plugin.py
src/main/python/pybuilder/reactor.py
src/unittest/python/plugins/python/distutils_plugin_tests.py

Added `distutils_upload_register` with `False` by default, since explicit registration is now deprecated.
fixes #503

Switch upload from setuptools to Twine (~=1.9)

---

src/main/python/pybuilder/vcs.py

implement PyBuilder access to git describe

---

src/integrationtest/python/integrationtest_support.py
src/main/python/pybuilder/plugins/python/coverage_plugin.py
src/main/python/pybuilder/plugins/python/distutils_plugin.py
src/main/python/pybuilder/plugins/python/unittest_plugin.py

Seems like flake8 has become more pedentic or something. These warnings are breaking current pull-requests, so fix them here.

fix four flake8 warnings

---

src/integrationtest/python/integrationtest_support.py
src/integrationtest/python/should_ignore_hidden_files_in_scripts_tests.py
src/main/python/pybuilder/plugins/python/core_plugin.py

Solves #608 and replaces #613 containing both tests for the issue and the fix for it.
The hard part was to determine that the byte `\x8a` is the magic byte that will crash `bdist_wheel`.

Fix ignore hidden files in scripts

---

src/main/python/pybuilder/plugins/python/pylint_plugin.py
src/unittest/python/plugins/python/pylint_plugin_tests.py

This tries to behave exactly as the equivalent functionality from flake8.
The main reason for this is because https://github.com/AlexeySanko/pybuilder_pylint_extended is not compatible with the latest version of pylint. Also, see #629 .
It also makes more sense for the built-in plugin to be able to do this.

Add option to allow pylint to break the build when it finds any warnings

---

src/main/python/pybuilder/plugins/python/pylint_plugin.py
src/unittest/python/plugins/python/pylint_plugin_tests.py

Only consider lines that contain a reference to a python file as warnings.
The original PR considered anything in the pylint report as a warning. This is not true, for example the score is usually published even when there are no errors.
Ideally we would use the json output from pylint to do this. This is not possible, because the users pylint settings might be different. For example most projects just use text input, and I want to avoid changing this just for pybuilder. We can do it if preferable, though..
This PR only looks for a python file being mentioned and assumes that is a one warning.
I have also modified the tests and also tested this locally on a project that needs the feature.

Fix bug on DEFAULT_PYLINT_BREAK_BUILD functionality

---

.travis.yml
src/main/python/pybuilder/plugins/python/core_plugin.py
src/unittest/python/plugins/python/core_plugin_tests.py

The sort order of the packages, modules and scripts must be stable across OSes

Fixing build stalls on OSX by using latest XCode

---

src/main/python/pybuilder/scaffolding.py
src/unittest/python/scaffolding_tests.py

Scaffolding doesn't need `install_dependencies` plugin in startup project

---

README.md
build.py
src/main/python/pybuilder/plugins/python/remote_tools/unittest_tool.py
src/main/python/pybuilder/plugins/python/unittest_plugin.py
src/main/python/pybuilder/python_utils.py
src/main/python/pybuilder/reactor.py
src/main/scripts/pyb
src/unittest/python/plugins/python/unittest_plugin_tests.py
travis/travis_shim.py

Remove sys.path manipulation from unittest plugin and move it into the
tool.
Update README.md.
filter plugin should only be touching $dir_dist.
Return all Travis production builds.
fixes #696

Fix `pybuilder` pyenv being appended instead of pre-pended to sys.path

---

src/main/python/pybuilder/plugins/python/unittest_plugin.py

fixes #704, fixes #706, fixes AlexeySanko/pybuilder_pytest#19

Return `_register_test_and_source_path_and_return_test_dir` to make PyTest plugin work

---

src/integrationtest/python/issue_737_tests.py
src/main/python/pybuilder/execution.py
src/unittest/python/execution_tests.py

TaskDependency.task may not be set during late dependency injection
Late dependency injection on a not-yet-existing task would fail to
log properly
Added various test to cover
fixes #737

Multiple fixes for late injection of dependencies

---

src/cmdlinetest/test_help.t
src/integrationtest/python/smoke_analyze_tests.py
src/integrationtest/python/smoke_install_dependencies_no_venvs_tests.py
src/integrationtest/python/smoke_install_dependencies_tests.py
src/integrationtest/python/smoke_sphinx_quickstart_tests.py
src/integrationtest/python/smoke_vendorize_tests.py
src/main/python/pybuilder/cli.py
src/main/python/pybuilder/core.py
src/main/python/pybuilder/plugins/python/core_plugin.py
src/main/python/pybuilder/reactor.py

Short-circuits all VEnv management logic defaulting to incorrect 0.11 behaviors
Also fix test names
fixes #746

Introduce `--no-venvs` option

---

src/integrationtest/python/issue_770_tests.py
src/main/python/pybuilder/plugins/python/remote_tools/unittest_tool.py
src/main/python/pybuilder/remote/__init__.py

Introduce a new opcode to indicate an exposed remote failure.
Ensure that failure is detected and handled appropriately in the unittest tool.
fixes #770

Make the failure in loading unit test modules a graceful one

---

src/integrationtest/python/issue_807_tests.py
src/main/python/pybuilder/extern/__init__.py

python/importlib_metadata#122 needs to be workedaround in 0.13
fixes #807

A bug in Python 3.8 importlib.metadata requires a workaround

---

build.py
src/integrationtest/python/issue_813_tests.py
src/main/python/pybuilder/plugins/python/core_plugin.py
src/main/python/pybuilder/plugins/python/integrationtest_plugin.py

Introduce the flag integrationtest_python_env_recreate (default to `False`) to
allow the user to control whether each integration test runs in a fresh
venv.
fixes #813

Revert to 0.12 behavior for integration test venv reuse

---

src/integrationtest/python/base_itest_support.py
src/main/python/pybuilder/remote/__init__.py

2. 3.11+ changed unittest.TestCase outcome/results internal API
fixes #856

1. 3.11+ requires mp.spawn.set_executable to be used

---

src/integrationtest/python/base_itest_support.py
src/integrationtest/python/issue_862_tests.py
src/main/python/pybuilder/plugins/python/coverage_plugin.py

Fix improper `class.filename` and `package.name` values on XML coverage report

---

src/integrationtest/python/issue_867_tests.py
src/integrationtest/python/itest_support.py
src/main/python/pybuilder/plugins/python/integrationtest_plugin.py

If integration test was running without any verbosity at all, an
exception would be thrown due to the missing report item.

Added 'exception' placeholder to report_item.

---

.github/workflows/pybuilder.yml
src/main/python/pybuilder/core.py
src/main/python/pybuilder/install_utils.py
src/main/python/pybuilder/plugins/python/distutils_plugin.py

Current functionality remains as is by default
`eager_update=True` forces dependency to always update on all installs
`eager_update=False` disables dependency updates even when version spec is non-exact

Add `eager_update` option to dependencies
